apiVersion: v2
name: n8n
description: A production-ready n8n Helm chart for K3s with Let's Encrypt SSL support
type: application
version: 1.0.0
appVersion: "1.4.1"
keywords:
  - n8n
  - workflow
  - automation
  - integration
  - postgres
  - k3s
  - letsencrypt
home: https://github.com/cagatayuresin/awesome-k3s-n8n-helm
sources:
  - https://github.com/cagatayuresin/awesome-k3s-n8n-helm
maintainers:
  - name: Cagatay Uresin
    url: https://github.com/cagatayuresin
